apiVersion: batch/v1
kind: Job
metadata:
  name: benchmarks-job
spec:
  ttlSecondsAfterFinished: 20
  template:
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: benchmarks-ctr
        image: alxlmsdn/honours:sniffers
        #arguments to the docker image 
        args: ["/data/config/configFile.txt", "/data/Reports/", "--sniffers", "cpu_bm"]
        volumeMounts:
        - mountPath: /data
          name: task-pv-storage
      restartPolicy: Never
  backoffLimit: 4