apiVersion: v1
kind: Pod
metadata:
  name: batik-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: dacapo-ctr
    image: stef3a/dacapo:latest
    #command: ["h2", "-s", "small", "-n", "1"]
    args: ["batik", "-s", "small", "-n", "1500"]
    ports:
    - containerPort: 5000
  restartPolicy: Never