apiVersion: v1
kind: Pod
metadata:
  name: xalan-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: dacapo-ctr
    image: stef3a/dacapo:latest
    #command: ["h2", "-s", "small", "-n", "1"]
    args: ["xalan", "-s", "large", "-n", "25"]
    ports:
    - containerPort: 5000
  restartPolicy: Never